config/routes.rb
Rails.application.routes.draw do

  root to: 'questions#index'

  get    'questions/unanswered', to: 'questions#unanswered'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  get    'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  get    'register',  to: 'users#new'

  resources :questions, except: [:delete] do
    post 'vote', on: :member
  end

  resources :comments, only: [:create, :edit, :update]

  resources :answers, only: [:create]

  resources :tags, only: [:index, :show]

  resources :users, only: [:show, :new, :create]
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
  has_many   :answers
  has_and_belongs_to_many   :tags
  has_many   :comments, as: :commentable
  has_many   :votes, as: :voteable

  validates :title, :body, :user, presence: true

  scope :most_voted, -> {
    order('votes_count DESC')
  }

  def add_tags(tag_string)
    tag_string = "" if tag_string.nil?
    tag_array = tag_string.strip.split(", ").map {
      |tag| Tag.where(text: tag).first_or_create
    }
    self.tags = tag_array
  end

  def tags_text
    self.tags.tags_text
  end

  def unchosen_answers
    if self.answer
      self.answers.where.not(id: self.answer.id).order('votes_count desc')
    else
      self.answers.order('votes_count desc')
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.most_voted
  end

  def new
    @question = Question.new
  end

  def create
    tags_text = params[:question].delete('tags_text')
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      @question.add_tags(tags_text)
      redirect_to @question
    else
      flash.now.alert = @question.errors.full_messages.join(', ')
      render 'questions/new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answer
    @answers = @question.unchosen_answers
    @comment = Comment.new
    @new_answer = Answer.new
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    tags_text = params[:question].delete('tags_text')
    @question = Question.find_by(id: params[:id])
    if @question.update(question_params)
      @question.add_tags(tags_text)
      redirect_to @question
    else
      flash.now.alert = @question.errors.full_messages.join(', ')
      render 'questions/edit'
    end
  end

  def unanswered
    @questions = Question.where("answer_id is ?", nil)
    render 'index'
  end

  def vote
    vote = current_user.votes.new(value: params[:value], voteable_id: params[:id], voteable_type: params[:type])
    if vote.save
      redirect_to :back, notice: "Vote accepted."
    elsif vote.has_voted?
      vote.existing_vote.update(value: vote.value)
      redirect_to :back, notice: "Vote updated."
    else
      redirect_to :back, alert: "Unable to vote on this."
    end
  end

  def destroy
    question = Question.find_by(id: params[:id])

    question.destroy
    flash[:notice] = "You've successfully deleted #{question.title}"
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/views/questions/_question.html.erb
<div class="row question">
  <div class="one column center-align">
    <div>
      <%= link_to "▲", vote_question_path(question, type: "Question", value: 1), method: "post" %>
    </div>
    <div>
      <%= question.votes_count %>
    </div>
    <div>
      <%= link_to "▼", vote_question_path(question, type: "Question", value: -1), method: "post" %>
    </div>
  </div>
  <div class="one column center-align">
    <%= pluralize(question.answers.count, "answer") %>
  </div>
  <div class="ten columns">
    <%= link_to question.title, question_path(question) %>
    <div class='row'>
      <div class='one-half column'>
        <%= render question.tags %>&nbsp;
      </div>
      <div class='one-half column right-align'>
        <%= link_to question.user.username, question.user %>
        <% if question.created_at == question.updated_at %>
          asked on <%= short_date(question.created_at.localtime) %>
        <% else %>
          updated on <%= short_date(question.updated_at.localtime) %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr>

app/views/questions/_question_form.html.erb
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'u-full-width' %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body, size: '80x12', class: 'u-full-width' %>
  </div>
  <div>
    <%= f.label :tags_text, "Tags (comma separated: example, 'ruby, rails')" %>
    <%= f.text_field :tags_text, class: 'u-full-width' %>
  </div>
  <%= f.submit class: 'button-primary' %>
<% end %>

app/views/questions/edit.html.erb
<h4>Edit your question</h4>
<%= render "question_form" %>

app/views/questions/index.html.erb
<h5>Top Questions</h5>

<% @questions.each do |question| %>
  <%= render partial: 'question', locals: {question: question} %>
<% end %>

app/views/questions/new.html.erb
<h4>Ask a question</h4>
<%= render "question_form" %>

app/views/questions/show.html.erb
<div id="question-header">
	<h4><%= @question.title %></h4>
</div>
<div class="row">
	<div class="one column center-align">
		<div>
			<%= link_to "▲", vote_question_path(@question, type: "Question", value: 1), method: "post" %>
		</div>
		<div>
			<%= @question.votes_count %>
		</div>
		<div>
			<%= link_to "▼", vote_question_path(@question, type: "Question", value: -1), method: "post" %>
		</div>
	</div>
	<div class="eleven columns">
		<%= @question.body %>
    <div class='row'>
      <div class='one-half column'>
        <%= render @question.tags %>&nbsp;
      </div>
      <div class='one-half column right-align'>
        Question by <%= link_to @question.user.username %>
        <% if @question.created_at == @question.updated_at %>
          asked on <%= short_date(@question.created_at.localtime) %>
        <% else %>
          updated on <%= short_date(@question.updated_at.localtime) %>
        <% end %>
			  <% if current_user == @question.user %>
			    <%= link_to "Delete Question", @question, method: :delete %>
			  <% end %>
      </div>
    </div>
	</div>
</div>
<hr>
<div class='row'>
	<div class='ten columns offset-by-two'>
		<h6><%= pluralize(@question.comments.count, "Comment") %></h6>
	</div>
</div>
<%= render @question.comments %>
<div class='row'>
	<div class='ten columns offset-by-two'>
		<%= form_for @comment, url: comments_path(question_id: @question) do |f| %>
		  <p>
		    <%= f.label :Comment %><br>
		    <%= f.text_area :body, class: 'u-full-width'%>
		  </p>
		  <p>
		    <%= f.submit class: 'button-primary' %>
		  </p>
		<% end %>
	</div>
</div>
<hr>
<div >
	<h5><%= pluralize(@question.answers.count, "Answer") %></h5>
</div>
<% if @answer %>
	<%= render @answer %>
	<div class='row'>
		<div class='ten columns offset-by-two'>
			<h6><%= pluralize(@answer.comments.count, "Comment") %></h6>
		</div>
	</div>
	<%= render @answer.comments %>
	<%= form_for @comment, url: comments_path(answer_id: @answer) do |f| %>
	  <p>
	    <%= f.label :Comment %><br>
	    <%= f.text_area :body, class: 'u-full-width' %>
	  </p>
	  <p>
	    <%= f.submit class: 'button-primary' %>
	  </p>
	<% end %>
	<hr>
<% end %>
<% if @answers %>
	<% @answers.each do |answer| %>
		<%= render answer %>
		<div class='row'>
			<div class='ten columns offset-by-two'>
				<h6><%= pluralize(answer.comments.count, "Comment") %></h6>
			</div>
		</div>
		<%= render answer.comments %>
		<div class='row'>
			<div class='ten columns offset-by-two'>
				<%= form_for @comment, url: comments_path(answer_id: answer) do |f| %>
				  <p>
				    <%= f.label :Comment %><br>
				    <%= f.text_area :body, class: 'u-full-width' %>
				  </p>
				  <p>
				    <%= f.submit class: 'button-primary' %>
				  </p>
				<% end %>
			</div>
		</div>
		<hr>
	<% end %>
<% end %>
<h5>Your Answer</h5>
<%= form_for @new_answer, url: answers_path(question_id: @question) do |f| %>
  <p>
    <%= f.label :Answer %><br>
    <%= f.text_area :body, class: 'u-full-width'%>
  </p>
  <p>
    <%= f.submit class: 'button-primary' %>
  </p>
<% end %>