config/routes.rb
Rails.application.routes.draw do

  root to: 'questions#index'

  get    'questions/unanswered', to: 'questions#unanswered'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  get    'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  get    'register',  to: 'users#new'

  resources :questions, except: [:delete] do
    post 'vote', on: :member
  end

  resources :comments, only: [:create, :edit, :update]

  resources :answers, only: [:create]

  resources :tags, only: [:index, :show]

  resources :users, only: [:show, :new, :create]
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :questions

  validates :text, presence: true

  def self.tags_text
    self.all.pluck(:text).join(', ')
  end
end

app/controllers/tag_controller.rb
class TagsController < ActionController::Base
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find_by(id: params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.order(:text)
  end

  def show
    @tag = Tag.find_by(id: params[:id])
    @questions = @tag.questions
  end
end

app/views/tags/_tag.html.erb
<%=  link_to tag.text, tag_path(tag), class: "post-tag" %>

app/views/tags/index.html.erb
<h4>Browse Questions by Tag</h4>
<div class="tag-columns">
  <ul>
    <% @tags.each do |tag| %>
      <li><%= render partial: 'tag', locals: { tag: tag } %></li>
    <% end %>
  </ul>
</div>

app/views/tags/show.html.erb
<h4>Browse All Questions Tagged <%= @tag.text.upcase %></h4>
<hr>
<% @questions.each do |question| %>
  <%= render partial: '/questions/question', locals: { question: question } %>
<% end %>