config/routes.rb
Rails.application.routes.draw do

  root to: 'questions#index'

  get    'questions/unanswered', to: 'questions#unanswered'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  get    'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  get    'register',  to: 'users#new'

  resources :questions, except: [:delete] do
    post 'vote', on: :member
  end

  resources :comments, only: [:create, :edit, :update]

  resources :answers, only: [:create]

  resources :tags, only: [:index, :show]

  resources :users, only: [:show, :new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turtle Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<header>
  <div class='container row'>
    <div class='one-third column'>
      <h1><%= link_to 'turtle overflow', root_path %></h1>
    </div>
    <div class='two-thirds column'>
      <div class='user-links'>
        <% if logged_in? %>
          <%= link_to current_user.username, current_user %> |
          <%= link_to 'logout', logout_path, method: :delete %>
        <% else %>
          <%= link_to "Register", register_path  %> |
          <%= link_to "Log in", login_path %>
        <% end %>
      </div>
      <div class="navigation-links">
        <%= link_to "Questions", questions_path, class: 'button' %>
        <%= link_to "Tags", tags_path, class: 'button' %>
        <%= link_to "Unanswered Questions", "questions/unanswered", class: 'button' %>
        <%= link_to "Ask a Question", new_question_path, class: 'button' %>
      </div>
    </div>
  </div>
</header>
<body>
  <div class='container'>
    <% if flash.any?  %>
      <div id="flash">
        <% flash.each do |type, message| %>
          <%= content_tag :div, message, class: type %>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>